### ISSUE TITLE
builder dla 4MB flash i większych ?

### ISSUE THREAD

**Issue by Hrumque** [krycha88/GUI-Generic#69]
Na https://gui-generic-builder.supla.io/ widzę tylko 2 opcje wielkości flash-u : 1MB i 2MB.
Nie wiem czy to ma jakikolwiek sens (bo i tak tych 2MB jak na razie nie zajmujemy chyba, a raczej brak RAMu jest ograniczeniem) - ale mam sporo modułów z 4MB flashu, a nawet 16MB - czy ma to znaczenie, by kompilować od razu z ustawionymi tak dużymi flashami? 
Oczywiście gdy teraz kompiluję na 1MB a wgrywam do 4MB - wszystko działa...

**Comment by krycha88** [comment]
Ma sens, bo GG nie zajmuje więcej niż 1MB. Jeżeli byś wgrywał sofy skompilowany dla 1MB na 2MB to stracisz konfigurację itd. a tak masz tylko dwie wielkości do wyboru to mniejsze prawdopodobieństwo, że się pomyślisz.
