### ISSUE TITLE
Dodać obsługę Wake on LAN :-)

### ISSUE THREAD

**Issue by arturniescior** [krycha88/GUI-Generic#78]

**Comment by Hrumque** [comment]
Ale co konkretnie w temacie WakeOnLan?
Możliwość wysyłania MagicPacket po stronie supla-device ? (po co?)
Możliwość budzenia ESP przez WakeOnLan (przez wifi) - jeszcze bardziej bez sensu, jak esp idzie w deepsleep to żadne wakeonlan go nie obudzi, a jak nie jest deepsleep - to co ma WakeOnLan zrobić? Odebranie WakeOnLan na adres Mac naszego ESP - ma udawać Wyzwalacz akcji, robić za przycisk?

**Comment by arturniescior** [comment]
Chodziło mi o odpalanie np komputera za pomocą WoL

**Comment by djgprv** [comment]
W routerze nie masz takiej opcji?

**Comment by djgprv** [comment]
Wake On LAN Library (ESP8266 & ESP32) - https://github.com/a7md0/WakeOnLan
MIT License

**Comment by krycha88** [comment]
Zostało zrealizowane
https://github.com/krycha88/GUI-Generic/commit/087e7c152beafe3e7172a59d5c0fc2b4679ec9f1
