### ISSUE TITLE
(multi) DS18b20 - pokazywanie mac i zmierzonej temperatury wprost od razu w WWW konfiguratorze device

### ISSUE THREAD

**Issue by Hrumque** [krycha88/GUI-Generic#81]
Gdy w konfigu WWW urządzenia ustawimy >1 czujników DS18b20 - można kliknąć w nazwę i wchodzi się w zapisywanie DSów wg znalezionego numeru MAC 
Jest to bardzo fajne, bo od razu pokazuje MAC (czyli - wiemy czy naprawdę znaleziono czujnik DS, i po MACu można dojść czy to jest w ogóle DS18b20, czy DS18s20 itp) , po drugie - pokazuje tam już zmierzoną temperaturę! 

Niestety - gdy mamy tylko jeden czujnik - takiej wygody nie zaznamy. Dlaczego? 
Czy po włączeniu sztuk1, i wybraniu gpio dla 1wire -  nie mogłoby tak samo pokazywać - wchodzić w listę znalezionych urządzeń 1wire dallas, i co one mierzą, mimo że jest tylko jedno?

**Comment by krycha88** [comment]
Jak wybierasz jeden czujnik to nie działam na MAC sensora, wykrywam go automatycznie przy starcie urządzenia. MAC jest potrzebny przy wielu sensorach na jednym GPIO.
