### ISSUE TITLE
Rolety - osobny przycisk UP, osobny DOWN 

### ISSUE THREAD

**Issue by Hrumque** [krycha88/GUI-Generic#83]
Po ustawieniu w builderze Rolety, i skonfigurowaniu na www "rolety: N" dla N>0 - zmienia się sterowanie przekaźnikami (muszą być 2, jeden do góry, drugi na dół - logiczne). Zmienia się też obsługa przycisków - i tu jest coś nielogicznie
Napisałem o tym też tu: https://forum.supla.org/viewtopic.php?p=128625#p128625

Gdy mamy wybrany 1 przycisk - z automatu pojawia się drugi (też z nr1) z opisem STOP - on nawet działa ;) (jako awaryjny stop, czerwony grzybek, itp bezpieczeństwa). 
Ustawienie więcej (np 2) przycisków - drugi przycisk nie posiada funkcji, nie ma czym sterować - bo oba przekaźniki są zajęte funkcją "roletową" i nie ma dla przycisku zastosowania... 

Ale to chyba nie tak powinno wyglądać sterowanie roletami? Powinny być dwa przyciski - jeden do góry, drugi na dół (jak zresztą nawet ma fabryczny moduł Zamel SRW01) - a nie sterowanie jednym przyciskiem w oba kierunki naprzemiennie. Trzeci - stop - jest też bardzo mądrą możliwością - więc niech zostanie... 

EDIT: Okazuje się- że trzeba dodać ten drugi przycisk (pomimo, że po jego dodaniu - nie ma  dla niego funkcji w konfiguratorze, pozornie), i wtedy to działa jak piszę powyżej.
 Bardzo to nieintuicyjne, chyba powinno być inaczej to opisane w WWW konfiguratorze?

**Comment by krycha88** [comment]
Dodałem małe usprawnienia
https://github.com/krycha88/GUI-Generic/commit/ef15140325bc96cddcf09c4f1ed7e764d971adb1
